apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: mini-node-exporter
    prometheus.io/scrape: "true"
  name: mini-node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mini-node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mini-node-exporter
    spec:
      hostNetwork: true
      containers:
      - image: mostafaelmenbawy/mini-node-exporter:latest
        imagePullPolicy: IfNotPresent
        name: mini-node-exporter
        ports:
        - containerPort: 23333
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 200Mi
