apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mini-node-exporter
  name: mini-node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mini-node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mini-node-exporter
    spec:
      hostNetwork: true
      containers:
      - image: mostafaelmenbawy/mini-node-exporter:latest
        imagePullPolicy: IfNotPresent
        name: mini-node-exporter
        # ports:
        # - containerPort: 23333
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 200Mi
