apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
## For production code a secret management tool should be use as sealed secrets or helm secrets
stringData:
  admin-user: admin
  admin-password: admin
